### ISSUE TITLE
If refreshrate <10s status won´t be updated

### ISSUE THREAD

**Issue by philoxio** [Zefau/ioBroker.nuki2#14]
If you put the refreshrate <10s the status won´t be updated.

AFAIK this is a limitation from Nuki and is not a bug of the adapter.

**Comment by Zefau** [comment]
This is related to the adapter, so it won't call the API too many times in a row.

This is because the calls are asynchronous so the answer will be received with a delay.

I can rewrite the code though, so that the refresh will still be executed and not omitted.

**Comment by Zefau** [comment]
With v0.9.11 I have added an info-message and a fallback to 10 seconds if less than 10 seconds have been setup.
Thanks for reporting the issue.
