### ISSUE TITLE
Problem updating states when having two (or more?) locks

### ISSUE THREAD

**Issue by Tom-OOE** [Zefau/ioBroker.nuki2#19]
iobroker on windows. 
Adapter "Nuki Smart Lock 2.0", 1.0.3

I am using two locks and one bridge. Controlling locks via smartphone app works just fine. 

Nuki-adapter can connect and is populating object tree in iobroker as expected. 

![image](https://user-images.githubusercontent.com/54640142/63879405-f48df980-c9cb-11e9-8670-26c4b94d19fe.png)

Problem is that subsequent status updates are just done for one of the locks. One lock is called "garage" and the other one is called "haupteingang". Analysing the debug log it seems to me that both, the states of the garage-lock and the haupteingang-lock, are written to the garage-lock-states. So haupteingang-lock-states never gets updated.

**Comment by Tom-OOE** [comment]
A screenshot of the debug log shows that door__garage.name is updated with wrong info:

![image](https://user-images.githubusercontent.com/54640142/63881408-16897b00-c9d0-11e9-9885-cc1ae825fd0a.png)

**Comment by Zefau** [comment]
Thanks for the info. I will look at this soon and fix it.

**Comment by Zefau** [comment]
Apparently Github is closing an issue when I reference it in a commit.

However, could you please install the current version from Github and see if the issue got resolved?
Thanks

**Comment by Tom-OOE** [comment]
Adapter 1.0.4 works as expected with two NUKI locks. Thank you!
