### ISSUE TITLE
door sensor does not update v1.0.3

### ISSUE THREAD

**Issue by senger1985** [Zefau/ioBroker.nuki2#20]
After I had to reset my Smart Lock because it was not displayed correctly in the Android app, the door sensor will no longer display values and there will be no updates after changes

Update (in seconds) = 20 seconds
![nuki2](https://user-images.githubusercontent.com/35745035/63999353-9106e780-cb03-11e9-89f0-c4e76bfdf31d.PNG)

**Comment by Zefau** [comment]
How come you closed it?

**Comment by senger1985** [comment]
Smart Lock reset again was helpful

**Comment by senger1985** [comment]
Please open again.
After some time the object "doorstate" shows "UNAVAILABLE" and "lastAction" "UNLATCH"
After the restart, the correct state is briefly displayed and then changes back to "UNAVAILABLE".

App settings is correct and show the correct states.

**Comment by senger1985** [comment]
I could find out something.
I do not know why but on web.nuki.io my smart lock and opener were not available.
Remote access was enabled.
What have I Done:
Remote access disabled and reactivated.
Now the stats are displayed correctly again

I will watch it and report you if the stats are wrong again

**Comment by senger1985** [comment]
Tested one week and everything works

**Comment by Zefau** [comment]
Great, thank you very much! I appreciate the feedback. Cheers
