### ISSUE TITLE
Wrong implementation has an impact on other Nuki-connected gateways

### ISSUE THREAD

**Issue by hblaschka** [Zefau/ioBroker.nuki2#21]
Hi there,

seems your implementation is buggy and thereby influences the behaviour of the Nuki Bridge when being connected to another device (here: homee Smart Home Gateway).

Seems the bridge sends a HTTP Request to ioBroker, which will not be answered correctly (no status 200 response). These leads to the effect that the bridge keeps on waiting for an answer, which never arrives. And this results in the behaviour described on the homee community starting here:

https://community.hom.ee/t/nuki-sperr-zustand-wird-oft-falsch-angezeigt/23353/11?u=hblaschka

Technical details can be discussed via PM with Tankred (@tankred) or Pascal (@pascal), two of the homee Devs on the homee Community or on the above mentioned thread.

Cross posted on https://github.com/smaragdschlange/ioBroker.nuki/ - same behaviour there.

**Comment by Zefau** [comment]
Thanks for the valuable information. I added a HTTP status response. Could you please test the current version from Github (version number is still v1.0.3). Thanks.

**Comment by hblaschka** [comment]
I am currently not using ioBroker on a productive system, but I will ask in the community.

**Comment by bergjet** [comment]
It's all right now, thank you.
