### ISSUE TITLE
No lock-states

### ISSUE THREAD

**Issue by DanielHD80** [Zefau/ioBroker.nuki2#22]
Hello,

I have installed a Nuki Combo 2.0 - weeks ago I had door- and lock-states. Now I was creating a Blockly and needed the lock-state, but it isn't there anymore? Bug in my system?
![nuki](https://user-images.githubusercontent.com/5008845/64726602-5031aa00-d4d7-11e9-9784-7bce9537bd51.png)

Daniel

**Comment by Zefau** [comment]
Do you have the bridge API connected as well or only the Web API?

**Comment by DanielHD80** [comment]
if you do it right, it works immediately ... thank you!

**Comment by Zefau** [comment]
What do you mean? Is it solved?
