### ISSUE TITLE
Core Files/Testing Update and introduce adapter-core

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.nuki2#3]
@Apollon77 Could you please create a pull request for the new core files / testing update?

Same as in https://github.com/Zefau/ioBroker.roomba/pull/8

Thanks in advanced,
Zefau

**Comment by Apollon77** [comment]
will do tonight

**Comment by Zefau** [comment]
@Apollon77 little Reminder. If you have the time this weekend it is much appreciated. I know you have a lot of other stuff on your agenda :-)

**Comment by Apollon77** [comment]
done https://github.com/Zefau/ioBroker.nuki2/pull/4

Sorry, lost from radar

**Comment by Zefau** [comment]
Thank you very much

**Comment by Zefau** [comment]
@Apollon77 One last thing: The link for the stable badge http://iobroker.live/badges/nuki2-stable.svg always redirects to another repository http://iobroker.live/badges/nuki-stable.svg and thus shows wrong version of this adapter. Where to open an issue for this? https://github.com/ioBroker/ioBroker/issues ?

**Comment by Apollon77** [comment]
is nuki2 aready in stable? maybe put into stable and then it should not do that. Also AIsue in the ioBroker-repositories Project

**Comment by Zefau** [comment]
It's not in the stable repo. My bad. Thank you.
